### ISSUE TITLE
Add burn tax info to all views that require it

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/station#12]
WHAT: Show burn tax payed for every TX on all views that require it
WHY: Show end users that the tax was actually implemented
WHO: Classic Network end users

**Tasks:**
- [ ] Add 1.2% burn tax information to all components or views that require it.
- [ ] Check what other views would need to display the burn tax info.

**Acceptance criteria:**
- [ ] All relevant areas and views of the platform should show the correct burn tax amount.
